import "server-only"

/** Exam_venue_c → pruefungszentrum (FHM spec; extend when full list is provided). */
export const SUGAR_EXAM_VENUE: Record<string, string> = {
    "": "",
    "100": "Bamberg",
    "200": "Berlin",
    "300": "Bielefeld",
    "6300": "Düren",
    "400": "Frechen (bei Köln)",
    "500": "Hannover",
    "600": "Köln",
    "700": "Rostock",
    "800": "Schwerin",
    "900": "Online-University",
    "1000": "Hoyerswerda",
    "1100": "München",
    "1200": "Münster",
    "7800": "Waldshut",
    "1300": "Wien",
    "8100": "Bocholt",
    "8200": "Gronau",
    "1400": "BK",
    "1500": "Aachen/Berufskolleg für Wirtschaft und Verwaltung",
    "12500": "Ahaus/Berufskolleg Canisiusstift",
    "1600": "Berlin/EWF Europäische Wirtschaftsfachschule",
    "1700": "Berlin/Pestalozzi-Fröbel-Haus",
    "1800": "Biberach/Matthias-Erzberger-Schule",
    "1900": "Bielefeld/Rudolf-Rempel-Berufskolleg",
    "2000": "Datteln/Berufskolleg Ostvest",
    "2100": "Detmold/Dietrich-Bonhoeffer-Berufskolleg",
    "2200": "Delmenhorst/BBS 2 Kerschensteiner-Schule Delmenhorst",
    "2300": "Dillenburg/Kaufmännische Schulen Dillenburg",
    "2400": "Düsseldorf/Berufskolleg Bachstraße",
    "2500": "Einbeck/BBS Einbeck",
    "2600": "Fulda/Richard-Müller-Schule",
    "2700": "Fürstenwalde/Berufliche Schule Paula Fürst der FAWZ",
    "2800": "Hameln/Elisabeth-Selbert-Schule",
    "2900": "Hanau/Eugen-Kaiser-Schule",
    "3000": "Hannover/Alice-Salomon-Schule",
    "3100": "Herford/Friedrich-List-Berufskolleg",
}
