import "server-only"

/** studies_c → studiengang (German labels in JSON). */
export const SUGAR_STUDIES: Record<string, string> = {
    "": "",
    "6500": "B.A. Architektur- & Immobilienmanagement",
    "10500": "B.A. Automotive & Mobility Management",
    "14100": "B.Eng. Bauingenieurwesen",
    "300": "B.A. Betriebswirtschaft",
    "6800": "B.A. Bildungswissenschaften Primar- und Elementarpädagogik",
    "9500": "B.Sc. (Hons) Cyber Security",
    "600": "B.A. Digital Business Management",
    "11000": "B.Eng. Elektromobilität",
    "700": "B.Sc. Ergotherapie",
    "800": "B.A. Eventmanagement & Entertainment",
    "900": "B.A. Fashion Management",
    "11700": "B.A. Foto & Film",
    "14600": "B.A. Gesundheitsmanagement",
    "1100": "B.A. Handwerksmanagement",
    "1200": "B.Sc. Hebammenwissenschaft",
    "1300": "B.A. Heilpädagogik & inklusive Bildung",
    "13100": "B.A. Human Resource Management",
    "1400": "B.A. International Business Administration",
    "1500": "B.A. Kommunikationsdesign & Werbung",
    "9300": "B.Sc. Logopädie",
    "9800": "Fachkraft für Berufliche Orientierung - Fernstudium",
    "15000": "B.A. Management im Handwerk",
    "12800": "B.Eng. Management & Technology",
    "1600": "B.A. Marketing Management",
    "14300": "B.Eng. Mechatronik",
    "1800": "B.A. Medienmanagement & Innovation",
    "1900": "B.Sc. Medical Sports & Health Management",
    "2100": "B.A. Medienkommunikation & Journalismus",
    "2300": "B.Sc. Medienpsychologie",
    "8000": "B.A. Online Marketing & Digital Commerce",
    "8900": "B.Sc. Pflege & Management",
    "2500": "B.Sc. Physician Assistance",
    "2600": "B.Sc. Physiotherapie",
    "2800": "B.Sc. Psychologie",
    "13000": "B.Sc. Psychology",
    "11800": "B.Sc. Rescue Management",
    "3000": "B.A. Soziale Arbeit & Management",
    "3200": "B.A. Sozialpädagogik & Management",
    "7000": "B.A. Sportjournalismus & Sportmarketing",
    "8700": "B.A. Sportmanagement",
    "7200": "B.A. Vegan Food Management",
    "12200": "B.Sc. Wirtschaftsingenieur",
    "8100": "B.Eng. Wirtschaftsingenieur - dual",
    "3700": "B.Sc. Wirtschaftspsychologie",
    "3800": "M.A. Beratung und Sozialmanagement",
    "11100": "M.A. Berufspädagogik",
    "3900": "M.A. Crossmedia & Communication Management",
    "9700": "M.Sc. Cyber Security",
    "13200": "MBA EdTech Management",
    "11600": "MBA General Technology Management",
    "4000": "M.A. Global Mittelstand",
    "9900": "M.A. Grundschulpädagogik",
    "4100": "MBA Innovation & Leadership",
    "4300": "M.A. International Management",
    "9000": "M.A. International Management (english)",
    "12600": "M.Sc. International Technology Transfer Management (ITTM)",
    "4700": "MMA Mikronährstofftherapie & Regulationsmedizin",
    "10000": "M.A. Nachhaltigkeits- & Klimamanagement",
    "4800": "M.Sc. Personal- und Kommunikationspsychologie",
    "9100": "M.Sc. Physiotherapie - Muskuloskelettale Therapien",
    "4600": "M.Sc. Psychologie",
    "4500": "M.A. Soziale Arbeit - Professioneller Kinder- und Jugendschutz",
    "8500": "M.A. Strategische Kommunikation & Digitales Marketing",
    "14200": "M.Sc. Digital Transformation Management",
    "10700": "M.Sc. Physician Assistance Klinische Akut- und Notfallmedizin",
    "5000": "Doctor of Business Administration (DBA)",
    "5400": "Betriebswirt General Management (FHM) - Fernstudium",
    "5500": "Betriebswirt im Gesundheits- und Sozialwesen (FHM)",
    "5600": "Case Manager im Gesundheits- und Sozialwesen (FHM/DGCC)",
    "7700": "DaF-/DaZ-Lehrkraft (FHM)",
    "5700": "Fachkraft berufliche Rehabilitation (FHM)",
    "14400": "Inklusionsmanagement (Klasse 1-12)",
    "5800": "Integrationsmanagement (FHM) - Fernstudium",
    "12500": "International Foundation Year",
    "12700": "KI-Manager/in (FHM)",
    "14500": "KI-Management im Gesundheitswesen",
    "15100": "Kompaktkurs Nachhaltigkeitsmanagement & - berichterstattung",
    "5900": "Medical Based Manager (FHM)",
    "6100": "Nachhaltigkeitsmanager (FHM)",
    "6200": "Personalbetriebswirt (FHM)",
    "14800": "Resilienz & Kommunikation",
    "6300": "Reha-Ausbilder/ReZA (FHM)",
    "14700":
        "Fachberatung im Kinderschutz: Die insoweit erfahrene Fachkraft (FHM)",
    "12400": "Traumapädagogik (FHM)",
    "6000":
        "Zertifikatsstudiengang Mikronährstofftherapie & Regulationsmedizin (FHM)",
}
